/*
Package native is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /usr/local/google/home/singhavnish/go/pkg/mod/github.com/openconfig/ygot@v0.33.0/genutil/names.go
using the following YANG input files:
  - yang/vendor/cisco/xr/2431/Cisco-IOS-XR-switch-oper.yang
  - yang/vendor/cisco/xr/2431/Cisco-IOS-XR-switch-oper-sub1.yang
  - yang/vendor/cisco/xr/2431/Cisco-IOS-XR-fabric-plane-health-oper.yang
  - yang/vendor/cisco/xr/2431/Cisco-IOS-XR-fabric-plane-health-oper-sub1.yang
  - yang/vendor/cisco/xr/2431/cisco-semver.yang
  - yang/vendor/cisco/xr/2431/ietf-inet-types.yang

Imported modules were sourced from:
  - yang/vendor/cisco/xr/2431/...
*/
package native
