/*
Package openconfig is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /usr/local/google/home/singhavnish/go/pkg/mod/github.com/openconfig/ygot@v0.33.0/genutil/names.go
using the following YANG input files:
  - public/release/models/platform/openconfig-platform.yang
  - public/release/models/platform/openconfig-platform-common.yang
  - public/release/models/platform/openconfig-platform-integrated-circuit.yang
  - public/release/models/platform/openconfig-platform-pipeline-counters.yang
  - public/release/models/openconfig-extensions.yang
  - public/release/models/types/openconfig-yang-types.yang
  - public/release/models/types/openconfig-types.yang

Imported modules were sourced from:
  - public/release/models/...
  - public/third_party/...
*/
package openconfig

import (
	"reflect"

	"github.com/openconfig/ygot/ygot"
)

// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_OpenconfigAlarmTypes_OPENCONFIG_ALARM_SEVERITY": {
		1: {Name: "CRITICAL", DefiningModule: "openconfig-alarm-types"},
		2: {Name: "MAJOR", DefiningModule: "openconfig-alarm-types"},
		3: {Name: "MINOR", DefiningModule: "openconfig-alarm-types"},
		4: {Name: "UNKNOWN", DefiningModule: "openconfig-alarm-types"},
		5: {Name: "WARNING", DefiningModule: "openconfig-alarm-types"},
	},
	"E_OpenconfigPlatformTypes_COMPONENT_OPER_STATUS": {
		1: {Name: "ACTIVE", DefiningModule: "openconfig-platform-types"},
		2: {Name: "DISABLED", DefiningModule: "openconfig-platform-types"},
		3: {Name: "INACTIVE", DefiningModule: "openconfig-platform-types"},
	},
	"E_OpenconfigPlatformTypes_COMPONENT_REBOOT_REASON": {
		1: {Name: "REBOOT_CRITICAL_ERROR", DefiningModule: "openconfig-platform-types"},
		2: {Name: "REBOOT_POWER_FAILURE", DefiningModule: "openconfig-platform-types"},
		3: {Name: "REBOOT_USER_INITIATED", DefiningModule: "openconfig-platform-types"},
	},
	"E_OpenconfigPlatformTypes_ComponentLastPoweroffReasonTrigger": {
		1: {Name: "USER_INITIATED"},
		2: {Name: "SYSTEM_INITIATED"},
		3: {Name: "POWER_FAILURE"},
	},
	"E_OpenconfigPlatformTypes_ComponentRedundantRole": {
		1: {Name: "PRIMARY"},
		2: {Name: "SECONDARY"},
	},
	"E_OpenconfigPlatformTypes_ComponentRedundantRoleSwitchoverReasonTrigger": {
		1: {Name: "USER_INITIATED"},
		2: {Name: "SYSTEM_INITIATED"},
	},
	"E_OpenconfigPlatformTypes_OPENCONFIG_HARDWARE_COMPONENT": {
		1:  {Name: "BACKPLANE", DefiningModule: "openconfig-platform-types"},
		2:  {Name: "CHASSIS", DefiningModule: "openconfig-platform-types"},
		3:  {Name: "CONTROLLER_CARD", DefiningModule: "openconfig-platform-types"},
		4:  {Name: "CPU", DefiningModule: "openconfig-platform-types"},
		5:  {Name: "FABRIC", DefiningModule: "openconfig-platform-types"},
		6:  {Name: "FAN", DefiningModule: "openconfig-platform-types"},
		7:  {Name: "FAN_TRAY", DefiningModule: "openconfig-platform-types"},
		8:  {Name: "FAN_TRAY_CONTROLLER", DefiningModule: "openconfig-platform-types"},
		9:  {Name: "FRU", DefiningModule: "openconfig-platform-types"},
		10: {Name: "INTEGRATED_CIRCUIT", DefiningModule: "openconfig-platform-types"},
		11: {Name: "LINECARD", DefiningModule: "openconfig-platform-types"},
		12: {Name: "PORT", DefiningModule: "openconfig-platform-types"},
		13: {Name: "POWER_SUPPLY", DefiningModule: "openconfig-platform-types"},
		14: {Name: "SENSOR", DefiningModule: "openconfig-platform-types"},
		15: {Name: "STORAGE", DefiningModule: "openconfig-platform-types"},
		16: {Name: "TRANSCEIVER", DefiningModule: "openconfig-platform-types"},
		17: {Name: "WIFI_ACCESS_POINT", DefiningModule: "openconfig-platform-types"},
	},
	"E_OpenconfigPlatformTypes_OPENCONFIG_SOFTWARE_COMPONENT": {
		1: {Name: "BIOS", DefiningModule: "openconfig-platform-types"},
		2: {Name: "BOOT_LOADER", DefiningModule: "openconfig-platform-types"},
		3: {Name: "OPERATING_SYSTEM", DefiningModule: "openconfig-platform-types"},
		4: {Name: "OPERATING_SYSTEM_UPDATE", DefiningModule: "openconfig-platform-types"},
		5: {Name: "SOFTWARE_MODULE", DefiningModule: "openconfig-platform-types"},
	},
	"E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Action": {
		1: {Name: "LOG"},
		2: {Name: "LINECARD_REBOOT"},
		3: {Name: "LINECARD_OFFLINE"},
		4: {Name: "NPU_RESET"},
		5: {Name: "NPU_OFFLINE"},
		6: {Name: "GET_DIAGNOSTIC_INFO"},
		7: {Name: "ALARM"},
	},
	"E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Level": {
		1: {Name: "FATAL"},
		2: {Name: "MAJOR"},
		3: {Name: "MINOR"},
		4: {Name: "INFORMATIONAL"},
	},
}

// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
func initΛEnumTypes() {
	ΛEnumTypes = map[string][]reflect.Type{
		"/components/component/integrated-circuit/pipeline-counters/errors/fabric-block/fabric-block-error/state/action": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Action)(0)),
		},
		"/components/component/integrated-circuit/pipeline-counters/errors/fabric-block/fabric-block-error/state/level": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Level)(0)),
		},
		"/components/component/integrated-circuit/pipeline-counters/errors/host-interface-block/host-interface-error/state/action": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Action)(0)),
		},
		"/components/component/integrated-circuit/pipeline-counters/errors/host-interface-block/host-interface-error/state/level": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Level)(0)),
		},
		"/components/component/integrated-circuit/pipeline-counters/errors/interface-block/interface-block-error/state/action": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Action)(0)),
		},
		"/components/component/integrated-circuit/pipeline-counters/errors/interface-block/interface-block-error/state/level": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Level)(0)),
		},
		"/components/component/integrated-circuit/pipeline-counters/errors/lookup-block/lookup-block-error/state/action": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Action)(0)),
		},
		"/components/component/integrated-circuit/pipeline-counters/errors/lookup-block/lookup-block-error/state/level": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Level)(0)),
		},
		"/components/component/integrated-circuit/pipeline-counters/errors/queueing-block/queueing-block-error/state/action": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Action)(0)),
		},
		"/components/component/integrated-circuit/pipeline-counters/errors/queueing-block/queueing-block-error/state/level": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatform_Components_Component_IntegratedCircuit_PipelineCounters_Errors_FabricBlock_FabricBlockError_State_Level)(0)),
		},
		"/components/component/state/last-poweroff-reason/trigger": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatformTypes_ComponentLastPoweroffReasonTrigger)(0)),
		},
		"/components/component/state/last-reboot-reason": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatformTypes_COMPONENT_REBOOT_REASON)(0)),
		},
		"/components/component/state/last-switchover-reason/trigger": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatformTypes_ComponentRedundantRoleSwitchoverReasonTrigger)(0)),
		},
		"/components/component/state/oper-status": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatformTypes_COMPONENT_OPER_STATUS)(0)),
		},
		"/components/component/state/redundant-role": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatformTypes_ComponentRedundantRole)(0)),
		},
		"/components/component/state/temperature/alarm-severity": []reflect.Type{
			reflect.TypeOf((E_OpenconfigAlarmTypes_OPENCONFIG_ALARM_SEVERITY)(0)),
		},
		"/components/component/state/type": []reflect.Type{
			reflect.TypeOf((E_OpenconfigPlatformTypes_OPENCONFIG_HARDWARE_COMPONENT)(0)),
			reflect.TypeOf((E_OpenconfigPlatformTypes_OPENCONFIG_SOFTWARE_COMPONENT)(0)),
		},
	}
}
